### ISSUE TITLE
move TODOs to issues

### ISSUE THREAD

**Issue by marwahaha** [QAOAKit/QAOAKit#22]
I think it's better to keep "TODO"s in one place.

**Comment by rsln-s** [comment]
Agreed. "TODO"s will go away over the next week or so; I am starting to write the extended abstract and in doing so will finalize some missing todo items

**Comment by marwahaha** [comment]
Fixed in https://github.com/QAOAKit/QAOAKit/commit/506ad0f814a056db488ce1406b6c1478a98be367
