### ISSUE TITLE
Installation error - pynauty install error

### ISSUE THREAD

**Issue by mvchalupnik** [QAOAKit/QAOAKit#57]
Error during `pip install QAOAKit` on pynauty build:

```
gcc -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/src/pynauty/nautywrap.o src/nauty27r1/nauty.o src/nauty27r1/nautil.o src/nauty27r1/naugraph.o src/nauty27r1/schreier.o src/nauty27r1/naurng.o -L/usr/lib64 -lpython3.6m -o build/lib.linux-x86_64-3.6/pynauty/nautywrap.cpython-36m-x86_64-linux-gnu.so
  /usr/bin/ld: src/nauty27r1/naugraph.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
  /usr/bin/ld: final link failed: Nonrepresentable section on output
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pynauty
```

**Comment by rsln-s** [comment]
Can you please share Python version, operating system and whether you're using anaconda? Also, if you are on a computing cluster, please share loaded modules (`module list`)

**Comment by mvchalupnik** [comment]
I am using a computing cluster. No modules loaded. Python version 3.6.8. I'm not using anaconda but I am in a python virtual environment. 
Operating system: 3.10.0-1160.36.2.el7.x86_64

Cluster specs: 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    1
Core(s) per socket:    24
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8268 CPU @ 2.90GHz
Stepping:              7
CPU MHz:               1199.896
CPU max MHz:           3900.0000
CPU min MHz:           1200.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0-23
NUMA node1 CPU(s):     24-47

**Comment by rsln-s** [comment]
May I ask you to load gcc module and, in a clean environment, install pynauty with no binaries? 

`pip install --no-binary pynauty pynauty`

Then `pip install QAOAKit`

**Comment by mvchalupnik** [comment]
I get the same error as above when I run `pip install --no-binary pynauty pynauty`. So it would seem to be some incompatibility of pynauty with the cluster I'm working on.

**Comment by rsln-s** [comment]
My I ask you to try one more thing? 
```
conda create -n qaoa python=3
conda activate qaoa
conda install -c conda-forge pynauty 
```

**Comment by rsln-s** [comment]
Great to hear! Please let me know if installation succeeds and you can retrieve the optimal parameters for desired graphs. If so, I’ll close the issue
