### ISSUE TITLE
pynauty version issue

### ISSUE THREAD

**Issue by gioaca** [QAOAKit/QAOAKit#58]
Hi, 
I am trying to install QAOAKit but I got the following error:

(qaoa) prompt$ pip install QAOAkit
Collecting QAOAkit
  Using cached QAOAKit-0.1.13-py3-none-any.whl (18 kB)
  Downloading QAOAKit-0.1.12-py3-none-any.whl (18 kB)
  Downloading QAOAKit-0.1.11-py3-none-any.whl (15 kB)
Collecting qiskit>=0.28.0
  Downloading qiskit-0.36.1.tar.gz (13 kB)
Collecting QAOAkit
  Downloading QAOAKit-0.1.10-py3-none-any.whl (14 kB)
  Downloading QAOAKit-0.1.9-py3-none-any.whl (13 kB)
  Downloading QAOAKit-0.1.8-py3-none-any.whl (13 kB)
  Downloading QAOAKit-0.1.7-py3-none-any.whl (12 kB)
ERROR: Cannot install qaoakit==0.1.10, qaoakit==0.1.11, qaoakit==0.1.12, qaoakit==0.1.13, qaoakit==0.1.7, qaoakit==0.1.8 and qaoakit==0.1.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    qaoakit 0.1.13 depends on pynauty==1.0.0
    qaoakit 0.1.12 depends on pynauty==1.0.0
    qaoakit 0.1.11 depends on pynauty==1.0.0
    qaoakit 0.1.10 depends on pynauty==1.0.0
    qaoakit 0.1.9 depends on pynauty==1.0.0
    qaoakit 0.1.8 depends on pynauty==1.0.0
    qaoakit 0.1.7 depends on pynauty==1.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

Please, can you help me?

Thank you.

Best regards,
Giovanni Acampora

**Comment by jmlarson1** [comment]
This was resolved in 5ea3921
