### ISSUE TITLE
Installation error from h5py dependency of Qiskit 0.29.0

### ISSUE THREAD

**Issue by garymooney** [QAOAKit/QAOAKit#60]
OS: Windows 10
Python: 3.11
QAOAKit version: "0.1.13"

I followed your instructions for installing from source (+ virtual env):
git clone https://github.com/QAOAKit/QAOAKit.git
cd QAOAKit
python -m venv myprojectenv
myprojectenv\Scripts\activate.bat
pip install -e .

I get an error while installing the h5py dependency:
Collecting h5py<3.3.0
  Using cached h5py-3.2.1.tar.gz (368 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error
...

It looks like qiskit==0.29.0 does not install correctly on my computer. I tried recreating a fresh venv and only installing qiskit==0.29.0 and I get the same error. 

Any chance this could be updated to work on the latest qiskit version?

**Comment by rsln-s** [comment]
Thanks for reaching out! Can you try unpinning the qiskit version and installing? Specifically, replace this line (https://github.com/QAOAKit/QAOAKit/blob/4cbb6c0cc398c38fa97db40976de104618b4bb4a/setup.py#L23) with `"qiskit"' (no version).

**Comment by garymooney** [comment]
Hi @rsln-s, 

I tried that and ended up getting more errors that I can't remember the details about. However, it looks like pynauty is not compatible with Windows anyway. So I'm in the process of creating a docker image, without the qiskit version requirement like you suggested. It's looking promising :).

**Comment by garymooney** [comment]
I can confirm that it's working correctly with the latest version of Qiskit when removing version restriction "qiskit==0.29.0". I install pynauty and qiskit before installing the locally modified QAOAKit when building my python:3.8-slim-buster docker image.
